const DEFAULT_STORE_NAME = process.env.NEXT_PUBLIC_STORE_NAME || "Your Store";

export const DEFAULT_SITE_CHROME = {
  header: {
    announcementShipping: "Free standard shipping on orders over $100",
    announcementSupport: "Thoughtful support within 24\u201348 hours",
    announcementSeparator: "\u2022",
    searchPlaceholder: "Search products, categories, and stories",
    searchButtonLabel: "Search",
    trackOrderLabel: "Track order",
    signInLabel: "Sign in",
    accountLabel: "Account",
    accountTooltip: "Account",
    signInTooltip: "Sign in",
    cartTooltip: "Shopping cart",
    shopAllLabel: "Shop all",
    trendingLabel: "Trending",
    categoriesLabel: "Categories",
    categoryHeading: "CATEGORIES",
    blogLabel: "Journal",
    aboutLabel: "About",
    helpLabel: "Help",
    helpTooltip: "Find answers for orders, shipping, returns, and account support.",
    categoryLinks: [
      { label: "Training", href: "/category/training" },
      { label: "Strength", href: "/category/strength" },
      { label: "Recovery", href: "/category/recovery" },
    ],
    aboutLinks: [
      { label: `About ${DEFAULT_STORE_NAME}`, href: "/aboutus" },
      { label: "How it works", href: "/how-it-works" },
      { label: `Why ${DEFAULT_STORE_NAME}`, href: "/why-weluxo" },
      { label: "FAQ", href: "/faq" },
    ],
    allProductsLabel: "All products",
    myAccountLabel: "My account",
    ordersLabel: "Orders",
    supportLabel: "Support",
    signOutLabel: "Sign out",
    helpCenterLabel: "Help center",
    mobileTrackOrderLabel: "Track an order",
    cartLabel: "Cart",
    mobileSearchPlaceholder: "Search the shop",
    yourCartLabel: "Your cart",
    cartReadyLabel: "Ready when you are",
    cartItemLabel: "item",
    cartItemsLabel: "items",
    closeCartLabel: "Close cart preview",
    emptyCartLabel: "Your cart is empty.",
    startShoppingLabel: "Start shopping",
    quantityLabel: "Qty",
    quantitySeparator: "\u00b7",
    subtotalLabel: "Subtotal",
    viewCartLabel: "View cart",
    checkoutLabel: "Checkout",
  },
  footer: {
    logoText: DEFAULT_STORE_NAME,
    brandDescription: "Thoughtful gear and guidance for the way you move.",
    trustItems: [
      { icon: "shipping", title: "Reliable delivery", copy: "Free standard shipping on orders over $100." },
      { icon: "support", title: "Thoughtful support", copy: "Real help from our team within 24\u201348 hours." },
      { icon: "secure", title: "Secure checkout", copy: "Protected payments and a clear order experience." },
    ],
    columns: {
      shopTitle: "Shop",
      supportTitle: "Support",
      companyTitle: "Company",
      legalTitle: "Legal",
    },
    shopLinks: [
      { label: "Shop", href: "/shop" },
      { label: "Trending", href: "/shop#trending-collection" },
      { label: "Training", href: "/category/training" },
      { label: "Strength", href: "/category/strength" },
      { label: "Recovery", href: "/category/recovery" },
    ],
    supportLinks: [
      { label: "Help center", href: "/help-center" },
      { label: "Contact us", href: "/contact" },
      { label: "Track an order", href: "/tracking" },
      { label: "Shipping information", href: "/shipping-information" },
      { label: "Returns & refunds", href: "/return-refund-policy" },
    ],
    companyLinks: [
      { label: "About us", href: "/aboutus" },
      { label: "How it works", href: "/how-it-works" },
      { label: `Why ${DEFAULT_STORE_NAME}`, href: "/why-weluxo" },
      { label: "Journal", href: "/blog" },
      { label: "FAQ", href: "/faq" },
    ],
    contact: {
      eyebrow: "Need a hand?",
      title: "We\u2019re here to help you move forward.",
      copy: "Questions about an order, product, or return? Our support team is ready.",
      buttonLabel: "Contact support",
      buttonHref: "/contact",
    },
    socials: [
      { platform: "facebook", label: "Facebook", href: "" },
      { platform: "instagram", label: "Instagram", href: "" },
      { platform: "twitter", label: "Twitter", href: "" },
      { platform: "linkedin", label: "LinkedIn", href: "" },
    ],
    legalLinks: [
      { label: "Privacy policy", href: "/privacy-policy" },
      { label: "Terms & conditions", href: "/terms-conditions" },
      { label: "Payment security", href: "/payment-security" },
    ],
    copyrightSuffix: "All rights reserved.",
    securityLabel: "Protected checkout",
    supportStatusLabel: "Helpful support",
    createdByLabel: "Created with",
    createdByName: "Nick Web Project",
    createdByHref: "https://nickwebproject.com",
  },
};

export async function fetchSiteChrome() {
  const response = await fetch("/api/site-chrome", { cache: "no-store" });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  return response.json();
}
