"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Alert, Box, Button, Chip, Container, Paper, Stack, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";

export default function SupportTicketList() {
  const [tickets, setTickets] = useState([]);
  const [error, setError] = useState("");
  const [filter, setFilter] = useState("active");
  useEffect(() => { fetch("/api/support/tickets", { credentials: "include" }).then((response) => response.ok ? response.json() : response.json().then((data) => Promise.reject(new Error(data.error || "Sign in required")))).then((data) => setTickets(data.tickets || [])).catch((loadError) => setError(loadError.message)); }, []);
  const visible = useMemo(() => tickets.filter((ticket) => filter === "all" || (filter === "active" ? !["Resolved", "Closed"].includes(ticket.status) : ["Resolved", "Closed"].includes(ticket.status))), [tickets, filter]);
  return <Box component="main" sx={{ bgcolor: "var(--color-background)", minHeight: "100vh", py: { xs: 3, md: 6 }, color: "var(--color-text-primary)" }}><Container maxWidth="md"><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={2} sx={{ mb: 3 }}><Box><Typography variant="overline" sx={{ color: "var(--color-primary)", fontWeight: 800, letterSpacing: "0.14em" }}>CUSTOMER DASHBOARD</Typography><Typography component="h1" sx={{ fontWeight: 850, fontSize: { xs: "2.5rem", md: "4rem" }, letterSpacing: "-0.05em", lineHeight: 1 }}>Support tickets</Typography><Typography sx={{ color: "var(--color-text-secondary)", mt: 1 }}>View active requests, closed tickets, and your support history.</Typography></Box><Button component={Link} href="/support/new-ticket" variant="contained" startIcon={<AddIcon />} sx={{ alignSelf: "flex-start", borderRadius: 999, bgcolor: "var(--color-primary)", textTransform: "none", fontWeight: 800 }}>New ticket</Button></Stack><Stack direction="row" spacing={1} sx={{ mb: 2 }}>{[["active", "Active"], ["closed", "Closed"], ["all", "All history"]].map(([value, label]) => <Button key={value} onClick={() => setFilter(value)} variant={filter === value ? "contained" : "outlined"} sx={{ borderRadius: 999, textTransform: "none", color: filter === value ? "#ffffff" : "var(--color-primary)", bgcolor: filter === value ? "var(--color-primary)" : "transparent", borderColor: "var(--color-primary)" }}>{label}</Button>)}</Stack>{error && <Alert severity="error" sx={{ mb: 2 }}>{error} <Button component={Link} href="/signin">Sign in</Button></Alert>}<Stack spacing={1.5}>{visible.map((ticket) => <Paper key={ticket.id} component={Link} href={`/support/tickets/${ticket.id}`} elevation={0} sx={{ display: "block", textDecoration: "none", color: "inherit", border: "1px solid var(--color-border)", borderRadius: 2.5, p: 2.5, "&:hover": { borderColor: "var(--color-primary)" } }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1}><Box><Typography sx={{ color: "var(--color-primary)", fontSize: 12, fontWeight: 800 }}>{ticket.ticketNumber}</Typography><Typography sx={{ fontWeight: 800, fontSize: 17 }}>{ticket.subject}</Typography><Typography sx={{ color: "var(--color-text-secondary)", fontSize: 13, mt: 0.5 }}>Last update: {ticket.updatedAt ? new Date(ticket.updatedAt).toLocaleString() : "-"}</Typography></Box><Chip label={ticket.status} sx={{ alignSelf: "flex-start", fontWeight: 750, bgcolor: ticket.status === "Closed" ? "#e2e8f0" : "var(--color-primary-soft)", color: "var(--color-text-primary)" }} /></Stack></Paper>)}{visible.length === 0 && <Paper elevation={0} sx={{ p: 3, border: "1px dashed var(--color-border)", bgcolor: "transparent" }}><Typography sx={{ color: "var(--color-text-secondary)" }}>No tickets in this view.</Typography></Paper>}</Stack></Container></Box>;
}
